# Generated by Django 3.0.1 on 2020-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.CharField(max_length=1),
        ),
    ]
