# Generated by Django 3.0.2 on 2020-02-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymarks', '0004_usermeta_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeta',
            name='is_completed',
        ),
    ]
